language: python
python:
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - git clone https://github.com/cmansley/pomdp-solve.git
  - pushd pomdp-solve && ./configure --prefix=/usr && make && sudo make install && popd
  - pip install -r requirements.txt
script:
  - python setup.py test
